import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

interface JobDescriptionReportProps {
  data: {
    jobDescription: string;
  };
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: "Helvetica",
    lineHeight: 1.5,
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    marginBottom: 30,
    textAlign: "center",
    color: "#666",
  },
  content: {
    fontSize: 12,
    whiteSpace: "pre-wrap",
  },
});

const JobDescriptionReport = ({ data }: JobDescriptionReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>Job Description</Text>
      <Text style={styles.subtitle}>
        Generated by AI JD Generator • {new Date().toLocaleDateString()}
      </Text>
      <Text style={styles.content}>{data.jobDescription}</Text>
    </Page>
  </Document>
);

export default JobDescriptionReport;
